/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccessRouteImport } from './routes/access'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardDashboardTeamRouteImport } from './routes/_dashboard.dashboard.team'
import { Route as DashboardDashboardOrdersRouteImport } from './routes/_dashboard.dashboard.orders'
import { Route as DashboardDashboardCodesRouteImport } from './routes/_dashboard.dashboard.codes'
import { Route as DashboardDashboardCatalogRouteImport } from './routes/_dashboard.dashboard.catalog'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardTeamRoute = DashboardDashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardOrdersRoute =
  DashboardDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardCodesRoute = DashboardDashboardCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardCatalogRoute =
  DashboardDashboardCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/catalog': typeof DashboardDashboardCatalogRoute
  '/dashboard/codes': typeof DashboardDashboardCodesRoute
  '/dashboard/orders': typeof DashboardDashboardOrdersRoute
  '/dashboard/team': typeof DashboardDashboardTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/catalog': typeof DashboardDashboardCatalogRoute
  '/dashboard/codes': typeof DashboardDashboardCodesRoute
  '/dashboard/orders': typeof DashboardDashboardOrdersRoute
  '/dashboard/team': typeof DashboardDashboardTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/access': typeof AccessRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_dashboard/dashboard/catalog': typeof DashboardDashboardCatalogRoute
  '/_dashboard/dashboard/codes': typeof DashboardDashboardCodesRoute
  '/_dashboard/dashboard/orders': typeof DashboardDashboardOrdersRoute
  '/_dashboard/dashboard/team': typeof DashboardDashboardTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/checkout'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/auth/callback'
    | '/dashboard/catalog'
    | '/dashboard/codes'
    | '/dashboard/orders'
    | '/dashboard/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/checkout'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/auth/callback'
    | '/dashboard/catalog'
    | '/dashboard/codes'
    | '/dashboard/orders'
    | '/dashboard/team'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/access'
    | '/checkout'
    | '/login'
    | '/register'
    | '/_dashboard/dashboard'
    | '/auth/callback'
    | '/_dashboard/dashboard/catalog'
    | '/_dashboard/dashboard/codes'
    | '/_dashboard/dashboard/orders'
    | '/_dashboard/dashboard/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AccessRoute: typeof AccessRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/team': {
      id: '/_dashboard/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardDashboardTeamRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/orders': {
      id: '/_dashboard/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardDashboardOrdersRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/codes': {
      id: '/_dashboard/dashboard/codes'
      path: '/codes'
      fullPath: '/dashboard/codes'
      preLoaderRoute: typeof DashboardDashboardCodesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/catalog': {
      id: '/_dashboard/dashboard/catalog'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardDashboardCatalogRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
  }
}

interface DashboardDashboardRouteChildren {
  DashboardDashboardCatalogRoute: typeof DashboardDashboardCatalogRoute
  DashboardDashboardCodesRoute: typeof DashboardDashboardCodesRoute
  DashboardDashboardOrdersRoute: typeof DashboardDashboardOrdersRoute
  DashboardDashboardTeamRoute: typeof DashboardDashboardTeamRoute
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardCatalogRoute: DashboardDashboardCatalogRoute,
  DashboardDashboardCodesRoute: DashboardDashboardCodesRoute,
  DashboardDashboardOrdersRoute: DashboardDashboardOrdersRoute,
  DashboardDashboardTeamRoute: DashboardDashboardTeamRoute,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AccessRoute: AccessRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
